'First_Name': 'Given Name'
'Middle_Name': 'Additional Name'
'Last_Name': 'Family Name'
'Title': 'Organization 1 - Title'
'Company': 'Organization 1'
'Address_Line_1': 'Address 1 - Street'
# 'Address_Line_2': ''
'City': 'Address 1 - City'
'State': 'Address 1 - Region'
'Zip_Code': 'Address 1 - Postal Code'
'Country': 'Address 1 - Country'
'2nd_Address_Line_1': 'Address 2 - Street'
# '2nd_Address_Line_2': ''
'2nd_City': 'Address 2 - City'
'2nd_State': 'Address 2 - Region'
'2nd_Zip_Code': 'Address 2 - Postal Code'
'2nd_Country': 'Address 2 - Country'
'Phone': 'Phone 1 - Value'
'Fax': 'Phone 5 - Value'
'Phone_-_Mobile': 'Phone 2 - Value'
'Phone_-_Home': 'Phone 3 - Value'
'Phone_-_Pager': 'Phone 4 - Value'
'Email': 'E-mail 1 - Value'
'Web_Page': 'Website 1 - Value'
'Email_1': 'E-mail 2 - Value'
'Email_2': 'E-mail 3 - Value'
'Email_3': 'E-mail 4 - Value'
'Notes': 'Notes'
# 'Categories': ''