names:
- "Name"
- "Given Name"
- "Additional Name"
- "Family Name"
- "Yomi Name"
- "Given Name Yomi"
- "Additional Name Yomi"
- "Family Name Yomi"
- "Name Prefix"
- "Name Suffix"
- "Initials"
- "Nickname"
- "Short Name"
- "Maiden Name"
emails:
  type: 
  - "E-mail 1 - Type"
  - "E-mail 2 - Type"
  - "E-mail 3 - Type"
  - "E-mail 4 - Type"
  value:
  - "E-mail 1 - Value"
  - "E-mail 2 - Value"
  - "E-mail 3 - Value"
  - "E-mail 4 - Value"
phones:
  type: 
  - "Phone 1 - Type"
  - "Phone 2 - Type"
  - "Phone 3 - Type"
  - "Phone 4 - Type"
  - "Phone 5 - Type"
  value:
  - "Phone 1 - Value"
  - "Phone 2 - Value"
  - "Phone 3 - Value"
  - "Phone 4 - Value"
  - "Phone 5 - Value"
addresses:
  type: 
  - "Address 1 - Type"
  - "Address 2 - Type"
  - "Address 3 - Type"
  formatted: 
  - "Address 1 - Formatted"
  - "Address 2 - Formatted"
  - "Address 3 - Formatted"
  street: 
  - "Address 1 - Street"
  - "Address 2 - Street"
  - "Address 3 - Street"
  city: 
  - "Address 1 - City"
  - "Address 2 - City"
  - "Address 3 - City"
  pobox: 
  - "Address 1 - PO Box"
  - "Address 2 - PO Box"
  - "Address 3 - PO Box"
  region: 
  - "Address 1 - Region"
  - "Address 2 - Region"
  - "Address 3 - Region"
  postal_code: 
  - "Address 1 - Postal Code"
  - "Address 2 - Postal Code"
  - "Address 3 - Postal Code"
  country: 
  - "Address 1 - Country"
  - "Address 2 - Country"
  - "Address 3 - Country"
  extended: 
  - "Address 1 - Extended Address"
  - "Address 2 - Extended Address"
  - "Address 3 - Extended Address"
websites:
  type: 
  - "Website 1 - Type"
  - "Website 2 - Type"
  - "Website 3 - Type"
  - "Website 4 - Type"
  - "Website 5 - Type"
  - "Website 6 - Type"
  - "Website 7 - Type"
  - "Website 8 - Type"
  - "Website 9 - Type"
  - "Website 10 - Type"
  - "Website 11 - Type"
  - "Website 12 - Type"
  - "Website 13 - Type"
  - "Website 14 - Type"
  - "Website 15 - Type"
  value: 
  - "Website 1 - Value"
  - "Website 2 - Value"
  - "Website 3 - Value"
  - "Website 4 - Value"
  - "Website 5 - Value"
  - "Website 6 - Value"
  - "Website 7 - Value"
  - "Website 8 - Value"
  - "Website 9 - Value"
  - "Website 10 - Value"
  - "Website 11 - Value"
  - "Website 12 - Value"
  - "Website 13 - Value"
  - "Website 14 - Value"
  - "Website 15 - Value"