- 'Name'
- 'Given Name'
- 'Additional Name'
- 'Family Name'
- 'Yomi Name'
- 'Given Name Yomi'
- 'Additional Name Yomi'
- 'Family Name Yomi'
- 'Name Prefix'
- 'Name Suffix'
- 'Initials'
- 'Nickname'
- 'Short Name'
- 'Maiden Name'
- 'Birthday'
- 'Gender'
- 'Location'
- 'Billing Information'
- 'Directory Server'
- 'Mileage'
- 'Occupation'
- 'Hobby'
- 'Sensitivity'
- 'Priority'
- 'Subject'
- 'Notes'
- 'Group Membership'
- 'E-mail 1 - Type'
- 'E-mail 1 - Value'
- 'E-mail 2 - Type'
- 'E-mail 2 - Value'
- 'E-mail 3 - Type'
- 'E-mail 3 - Value'
- 'E-mail 4 - Type'
- 'E-mail 4 - Value'
- 'IM 1 - Type'
- 'IM 1 - Service'
- 'IM 1 - Value'
- 'Phone 1 - Type'
- 'Phone 1 - Value'
- 'Phone 2 - Type'
- 'Phone 2 - Value'
- 'Phone 3 - Type'
- 'Phone 3 - Value'
- 'Phone 4 - Type'
- 'Phone 4 - Value'
- 'Phone 5 - Type'
- 'Phone 5 - Value'
- 'Address 1 - Type'
- 'Address 1 - Formatted'
- 'Address 1 - Street'
- 'Address 1 - City'
- 'Address 1 - PO Box'
- 'Address 1 - Region'
- 'Address 1 - Postal Code'
- 'Address 1 - Country'
- 'Address 1 - Extended Address'
- 'Address 2 - Type'
- 'Address 2 - Formatted'
- 'Address 2 - Street'
- 'Address 2 - City'
- 'Address 2 - PO Box'
- 'Address 2 - Region'
- 'Address 2 - Postal Code'
- 'Address 2 - Country'
- 'Address 2 - Extended Address'
- 'Address 3 - Type'
- 'Address 3 - Formatted'
- 'Address 3 - Street'
- 'Address 3 - City'
- 'Address 3 - PO Box'
- 'Address 3 - Region'
- 'Address 3 - Postal Code'
- 'Address 3 - Country'
- 'Address 3 - Extended Address'
- 'Organization 1 - Type'
- 'Organization 1 - Name'
- 'Organization 1 - Yomi Name'
- 'Organization 1 - Title'
- 'Organization 1 - Department'
- 'Organization 1 - Symbol'
- 'Organization 1 - Location'
- 'Organization 1 - Job Description'
- 'Website 1 - Type'
- 'Website 1 - Value'
- 'Website 2 - Type'
- 'Website 2 - Value'
- 'Website 3 - Type'
- 'Website 3 - Value'
- 'Website 4 - Type'
- 'Website 4 - Value'
- 'Website 5 - Type'
- 'Website 5 - Value'
- 'Website 6 - Type'
- 'Website 6 - Value'
- 'Website 7 - Type'
- 'Website 7 - Value'
- 'Website 8 - Type'
- 'Website 8 - Value'
- 'Website 9 - Type'
- 'Website 9 - Value'
- 'Website 10 - Type'
- 'Website 10 - Value'
- 'Website 11 - Type'
- 'Website 11 - Value'
- 'Website 12 - Type'
- 'Website 12 - Value'
- 'Website 13 - Type'
- 'Website 13 - Value'
- 'Website 14 - Type'
- 'Website 14 - Value'
- 'Website 15 - Type'
- 'Website 15 - Value'