'given_name': 'Given Name'
'family_name': 'Family Name'
'id': 'ID'
'nickname': 'Nickname'
'email_1': 'E-mail 1 - Value'
'email_2': 'E-mail 2 - Value'
'email_3': 'E-mail 3 - Value'
'email_4': 'E-mail 4 - Value'
# 'wants_html': 'IC'
'business_phone': 'Phone 1 - Value'
'home_phone': 'Phone 3 - Value'
'business_fax': 'Phone 5 - Value'
'pager': 'Phone 4 - Value'
'mobile_phone': 'Phone 2 - Value'
# 'Home Address':
# 'Home Address2':
'Home Address City': 'Address 1 - City'
'Home Address State': 'Address 1 - Region'
'Home Address PostCode': 'Address 1 - Postal Code'
'Home Address Country': 'Address 1 - Country'
# 'Business Address': ''
# 'Business Address2': ''
'Business Address City': 'Address 2 - City'
'Business Address State': 'Address 2 - Region'
'Business Address PostCode': 'Address 2 - Postal Code'
'Business Address Country': 'Address 2 - Country'
'title': 'Organization 1 - Title'
# 'office': ''
'org': 'Organization 1 - Name'
'homepage_url': 'Website 1 - Value'
# 'caluri': 'IC'
# 'Birth Year': 'IC'
# 'Birth Month': 'IC'
# 'Birth Day': 'IC'
'note': 'Notes'
