# 'Address 1':
# 'Address 2':
# 'Address 3':
# 'Address 3 Address 1': 
# 'Address 3 Address 2': 
# 'Address 3 Address 3': 
# 'Address 3 City': 
# 'Address 3 Country': 
# 'Address 3 State': 
# 'Address 3 ZIP Code': 
# 'Alternate Extension': 
# 'Alternate Phone': 
'Birth Date': 'Birthday'
'City': 'Address 1 - City'
'Company': 'Organization 1 - Name'
# 'Contact': 
'Country': 'Address 1 - Country'
# 'Create Date':
# 'Department': 
'Edit Date':''
'E-mail': 'E-mail 1 - Value'
# 'Extension': 
# 'Fax Extension': 
'Fax Phone': 'Phone 5 - Value'
# 'First Name': 
# 'Home Address 1':
# 'Home Address 2':
# 'Home Address 3':
# 'Home City':
# 'Home Country':
# 'Home Extension': 
'Home Phone': 'Phone 3 - Value'
# 'Home State':
# 'Home ZIP Code': 
# 'ID/Status': 
# 'Last Attempt': 
# 'Last Edited By': 
# 'Last E-mail': 
# 'Last Meeting': 
# 'Last Name': 
# 'Last Reach': 
# 'Last Results': 
# 'Letter Date': 
# 'Messenger ID': 
# 'Middle Name': 
# 'Mobile Extension': 
'Mobile Phone': 'Phone 2 - Value'
'Name Prefix': 'Name Prefix'
'Name Suffix': 'Name Suffix'
# 'Pager Extension': 
'Pager Phone': 'Phone 4 - Type'
'Personal E-mail': 'E-mail 2 - Value'
'Phone': 'Phone 1 - Value'
# 'Private': 
# 'Record Creator': 
# 'Record Manager': 
# 'Referred By': 
# 'Salutation': 
# 'Spouse': 
'State': 'Address 1 - State'
'Title': 'Organization 1 - Title'
# 'User 1': 
# 'User 10': 
# 'User 2': 
# 'User 3': 
# 'User 4': 
# 'User 5': 
# 'User 6': 
# 'User 7': 
# 'User 8': 
# 'User 9': 
'Web Site': 'Website 1 - Value'
'ZIP Code': 'Address 1 - Postal Code'
