work:
 - 'SA - Address 1'
 - 'SA - Address 2'
 - 'SA - Address 3'
home:
 - 'SA - Home Address 1'
 - 'SA - Home Address 2'
 - 'SA - Home Address 3'
other:
 - 'SA - Address 3 Address 1'
 - 'SA - Address 3 Address 2'
 - 'SA - Address 3 Address 3'
